# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jaydenprojects
service: fastapi-aws-lambda

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1 # Use your preferred AWS region
  memorySize: 512
  timeout: 10

functions:
  app:
    handler: api/main.handler # Entry point for AWS Lambda in main.py
    events:
      - httpApi: # API Gateway configuration for routing requests
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  exclude:
    - .next/**
    - node_modules/**
    - .serverless/**
    - .venv/**
